#!/bin/bash

#/ NAME
#/     rbenv -- 

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
[ -n "${RBENV_DEBUG:-}" ] && set -x

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${RBENV_ROOT:-}" ]; then
  RBENV_ROOT="${HOME}/.rbenv"
else
  RBENV_ROOT="${RBENV_ROOT%/}"
fi
export RBENV_ROOT

if [ -z "${RBENV_DIR:-}" ]; then
  RBENV_DIR="$(pwd)"
else
  cd "$RBENV_DIR" 2>/dev/null || {
    echo "rbenv: cannot change working directory to \`$RBENV_DIR'"
    exit 1
  } >&2
  RBENV_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export RBENV_DIR

PATH="$PATH:$shome/libexec"

require sub "$BASH_SOURCE" "$@"
