#!/usr/bin/env bash
set -e
[ -n "$RBENV_DEBUG" ] && set -x

# Provide rbenv completions
if [ "$1" = "--complete" ]; then
  echo --path
  exec rbenv shims --short
fi

if [ "$1" = "--path" ]; then
  print_paths="1"
  shift
else
  print_paths=""
fi

whence() {
  local command="$1"
  rbenv-versions --bare | while read version; do
    path="$(rbenv-prefix "$version")/bin/${command}"
    if [ ! -x "$path" ]; then
      RBENV_VERSION_ALT="$(basename $(readlink "${RBENV_ROOT}/versions/${version}" 2>&-) || true)"
      if [[ -z "$RBENV_VERSION_ALT" ]]; then
        RBENV_VERSION_ALT=$version
      fi
      path="$(cd -P -- "${RBENV_ROOT}/versions/${version}" && pwd -P)/../../gems/${RBENV_VERSION_ALT}/bin/$command"
    fi

    if [ -x "$path" ]; then
      [ "$print_paths" ] && echo "$path" || echo "$version"
    fi
  done
}

RBENV_COMMAND="$1"
if [ -z "$RBENV_COMMAND" ]; then
  echo "usage: rbenv whence [--path] COMMAND" >&2
  exit 1
fi

result="$(whence "$RBENV_COMMAND")"
[ -n "$result" ] && echo "$result"
