#!/usr/bin/env bash

# figure out the project root under which bin, lib live
rhome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/../.." && pwd -P)"

export RBENV_ROOT=$rhome/.rbenv
exec rbenv exec "${0##*/}" "$@"
